spring.application.name=FlagPulse

#PORT
server.port=8083

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/config_pulse_db?rewriteBatchedStatements=true&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Configurations
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Cache Type Specification
spring.cache.type=caffeine